data:  # data related config
  raw_data: "./artefacts/HousingData.csv"  # path to the input raw data used for the training process
  train_data_save_path: "./artefacts/train_data.csv"  # save path of the train split of the data - used for training the model
  test_data_save_path: "./artefacts/test_data.csv"   # save path of the test split of the data - used for testing the trained models performance
  val_data_save_path: "./artefacts/val_data.csv"   # save path of the validation split of the data - used for hyperparameter tuning
  label_col: "price"   # column name of the predictor variable
  categorical_cols: ["mainroad", "guestroom", "basement", "hotwaterheating",  # categorical column names in the input data
                   "airconditioning", "prefarea", "furnishingstatus"]
  numeric_cols: ["area", "bedrooms", "bathrooms", "stories", "parking"]   # numerical column names in the input data
  preprocessor_path: "./artefacts/preprocessor.joblib"   # save path of the preprocessing transformations (parameters are learned from the train data)

model:   # model related parameters and hyperparameters
  model_name: "house_price-regression"   # The name with which the model should be saved or logged
  save_path: "./artefacts/"   # model save path
  train_batch_size: 64    # model training batch size (number of data point in single training step/pass through the model)
  test_batch_size: 64   # model test/val batch size (number of data points in a single pass through the model)
  n_epochs: 1000    # number of epochs - how many times the model should pass through the entire training split of the data
  learning_rate: 0.01   # learning rate of the model optimiser
  es_patience: 10   # early stopping patience - how many more training epochs will be attempted if there is no improvement in model observed
  es_delta: 0   # early stopping delta - what increment in model performance will be considered as improvement for early stopping
  use_gpu: True   # to use gpu or not. If no gpu found, will fall back to cpu with warning

mlflow:  # for mlflow logging
  tracking_uri: "http://localhost:5000"   # MLFlow tracking uri. Use http://host.docker.internal:5000 if the MLFlow is running in a docker container
  expt_name: "expt-name"   # Experiment name under which the model trainings will be listed in MLFlow
